# Generated by Django 3.1.2 on 2020-12-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='age',
            field=models.IntegerField(default=20, verbose_name='年齢'),
            preserve_default=False,
        ),
    ]
